### ISSUE TITLE
When rust variable is used, you should omit `_`

### ISSUE THREAD

**Issue by shawntabrizi** [parity-samples/substrate-erc20-multi#5]
https://github.com/parity-samples/substrate-erc20-multi/blob/c5305b9a15b963529978862300b91d2720abeda1/runtime/src/erc20.rs#L33

So `_origin` should be `origin`

**Comment by gautamdhameja** [comment]
Fixed in 7bafdafc1f4afc1b0a733fc8d67a18b4bdbf1495. Closing.
